name = "Tella"
license = "MIT"
licenselink = "https://github.com/opera7133/tella/blob/master/LICENSE"
description = "Simple, Light, Responsive"

homepage = "https://github.com/opera7133/tella"
demosite = "https://tella.pages.dev"

tags = ["WizLegal", "AI Legal Automation"]
features = ["Portfolio", "slides", "responsive"]

[author]
  name = "wamo"
  homepage = "https://wmsci.com"
