baseURL = "https://wizlegal.io"
title = "WizLegal"
author = "Wiz Legal"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
googleAnalytics = "G-SE4861P0W2"

# Disqus Comment System
#disqusShortname = ""

[params]

  showBlog = true
  mainSections = ['blog']

  googleFonts = true

  [params.logo]
    main = "img/logo/wizlegal-logo.png"
    alt = "WizLegal Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "WizLegal"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "WizLegal leverages cutting-edge generative AI technologies to automate and streamline a wide range of legal tasks, from document review and legal research to contract analysis and due diligence"
    meta_og_title = "WizLegal - AI Powered Legal Automation"
    meta_og_type = "website"
    meta_og_url = "https://wizlegal.io/"
    meta_og_image = "img/logo/wizlegal-logo.png"
    meta_og_description = "WizLegal leverages cutting-edge generative AI technologies to automate and streamline a wide range of legal tasks, from document review and legal research to contract analysis and due diligence"
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@username1"
    meta_twitter_creator = "@username"

[menu]

  [[menu.main]]
    identifier = "blog"
    name = "Solutions"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 4

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Terms and Conditions"
    url = "/Terms and Conditions"
      weight = 2
